# Generated by slipway (cloud=azure, layer=foundation). Regenerate with the scaffold; do not hand-edit.
terraform {
  required_version = ">= 1.9"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 5.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 3.0"
    }
  }

  # State lives in the storage account created by .slipway/setup-azure.sh (shared-key access disabled):
  # authentication is Entra ID only. Locally: az login. In CI: OIDC (ARM_USE_OIDC=true).
  backend "azurerm" {
    resource_group_name  = "rg-taskflow-tfstate"
    storage_account_name = "sttaskflowtf"
    container_name       = "tfstate"
    key                  = "taskflow/foundation/dev.tfstate"
    use_azuread_auth     = true
  }
}
