#!/usr/bin/env bash
# Generated by slipway (do not hand-edit; re-render with scaffold.cjs). Install step of the Cursor Cloud Agent
# environment of this repository (.cursor/environment.json -> "install"). Cursor runs it while it builds the VM image,
# before any agent turn (cursor.com/docs/cloud-agent/setup and /builds, read 2026-09-27). Idempotent, committed, no secrets.
# What it does:
#   1. installs the slipway plugin at the version that rendered this repository into ~/.cursor/plugins/local/slipway,
#      the folder .slipway/cursor-hooks.sh looks in, so the guard hooks declared in .cursor/hooks.json are enforced in
#      the cloud exactly as on a desktop (cloud agents run the repository's command hooks, never plugin or user hooks);
#   2. marks the environment unattended (~/.cursor/slipway/unattended): cloud agents never run the sessionStart hook and
#      cannot answer a permission prompt, so administrative actions and terraform apply are denied instead of asked;
#   3. exports SLIPWAY_PLUGIN_ROOT / CLAUDE_PLUGIN_ROOT for the agent's shells, so the `node "${CLAUDE_PLUGIN_ROOT}/scripts/..."`
#      commands of a SKILL.md work when the agent follows one (skills are not slash commands in the cloud; see AGENTS.md);
#   4. installs the toolchain of .slipway/cloud-setup.sh when present (best effort; the guards need only bash and python3).
# Failure is loud: a missing plugin would leave the environment without guardrails, so this script fails the Build.
set -uo pipefail
PLUGIN_REPO="https://github.com/integranz/slipway"
PLUGIN_VERSION="1.6.0"
LOCAL="${CURSOR_PLUGINS_LOCAL:-$HOME/.cursor/plugins/local}/slipway"
STATE="${CURSOR_USER_SHIM_DIR:-$HOME/.cursor/slipway}"
SRC="$STATE/src"
mkdir -p "$STATE" "$(dirname "$LOCAL")"

# 1. plugin source at the pinned tag (fallback: the default branch, with a warning)
fetch() { rm -rf "$SRC"; git clone -q --depth 1 "$@" "$PLUGIN_REPO" "$SRC" 2>/dev/null; }
if fetch --branch "v$PLUGIN_VERSION"; then echo "slipway source: $PLUGIN_REPO at v$PLUGIN_VERSION"
elif fetch; then echo "WARN slipway tag v$PLUGIN_VERSION not found; using the default branch of $PLUGIN_REPO" >&2
else echo "ERROR cannot clone $PLUGIN_REPO: without the plugin the slipway guards are not enforced, so this Build fails on purpose (check network egress)" >&2; exit 1; fi
[ -f "$SRC/plugins/slipway/.cursor-plugin/plugin.json" ] || { echo "ERROR $SRC does not contain the slipway plugin" >&2; exit 1; }
mkdir -p "$LOCAL"
if command -v rsync >/dev/null 2>&1; then rsync -a --delete --exclude node_modules "$SRC/plugins/slipway/" "$LOCAL/"
else rm -rf "$LOCAL"; cp -R "$SRC/plugins/slipway" "$LOCAL"; fi
installed="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$LOCAL/.cursor-plugin/plugin.json" 2>/dev/null || echo unknown)"
echo "slipway plugin $installed -> $LOCAL"

# 2. unattended marker, read by the Cursor hook adapters when no session-start hook ran
printf 'cursor cloud agent environment; installed %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$STATE/unattended"

# 3. shell environment for the agent (interactive and login shells)
for rc in "$HOME/.bashrc" "$HOME/.profile"; do
  touch "$rc"; grep -v '# slipway cloud env$' "$rc" > "$rc.tmp" || true; mv "$rc.tmp" "$rc"
  printf 'export SLIPWAY_PLUGIN_ROOT="%s" CLAUDE_PLUGIN_ROOT="%s" SLIPWAY_SESSION_ATTENDED=0 SLIPWAY_HOST=cursor # slipway cloud env\n' "$LOCAL" "$LOCAL" >> "$rc"
done

# 4. toolchain (best effort)
if [ -f .slipway/cloud-setup.sh ]; then bash .slipway/cloud-setup.sh || echo "WARN .slipway/cloud-setup.sh failed; plan and verify steps may report UNVERIFIABLE" >&2; fi
for t in bash python3 node git docker gh terraform az; do
  if command -v "$t" >/dev/null 2>&1; then echo "tool: $t -> $(command -v "$t")"; else echo "tool: $t missing"; fi
done
echo "slipway cloud environment ready: unattended (administrative actions and terraform apply are denied), guards run from .cursor/hooks.json"
