#!/usr/bin/env bash
# Generated by slipway (do not hand-edit; re-render with scaffold.cjs). Routes this repository's Cursor project hooks
# (.cursor/hooks.json, run from the repository root) to the slipway plugin installed on this machine, so the delivery
# guardrails are enforced in Cursor as they are in Claude Code. Cursor 3.21.x loads hooks from the project, user, team
# and enterprise configurations, not from an installed plugin, which is why the repository carries this wiring.
# Usage: bash .slipway/cursor-hooks.sh <adapter>   adapter = pretooluse | shell | mcp | read | session-start
# Without the plugin the hooks allow everything and the session-start context says so: a developer who does not run
# slipway keeps a working Cursor, and the guards apply wherever slipway is installed.
set -u
adapter="${1:?usage: cursor-hooks.sh <adapter>}"
case "$adapter" in pretooluse|shell|mcp|read|write|session-start) ;; *) echo '{"permission":"deny","user_message":"slipway guard: unknown adapter"}'; exit 0;; esac
find_root() {
  local d
  if [ -n "${SLIPWAY_PLUGIN_ROOT:-}" ] && [ -f "$SLIPWAY_PLUGIN_ROOT/cursor/hooks/$adapter.sh" ]; then printf '%s' "$SLIPWAY_PLUGIN_ROOT"; return; fi
  if [ -f "$HOME/.cursor/plugins/local/slipway/cursor/hooks/$adapter.sh" ]; then printf '%s' "$HOME/.cursor/plugins/local/slipway"; return; fi
  # marketplace installs: ~/.cursor/plugins/cache/<owner-repo>/slipway/<commit>/, newest first
  d="$(ls -td "$HOME"/.cursor/plugins/cache/*/slipway/*/cursor/hooks 2>/dev/null | head -1)"
  if [ -n "$d" ]; then printf '%s' "${d%/cursor/hooks}"; return; fi
  # a Claude Code install of the same plugin carries the same adapters
  d="$(ls -td "$HOME"/.claude/plugins/cache/*/slipway/*/cursor/hooks 2>/dev/null | head -1)"
  if [ -n "$d" ]; then printf '%s' "${d%/cursor/hooks}"; return; fi
  printf ''
}
root="$(find_root)"
if [ -z "$root" ]; then
  if [ "$adapter" = session-start ]; then
    echo '{"additional_context":"slipway: the plugin is not installed in this Cursor, so its delivery guardrails are NOT enforced here. Install it before any delivery work (repository README, Install in Cursor); do not run terraform apply, cloud administration or secret writes from this session."}'
  else
    echo '{"permission":"allow"}'
  fi
  exit 0
fi
exec bash "$root/cursor/hooks/$adapter.sh"
