#!/usr/bin/env bash
# One-time Azure/Entra prerequisites for taskflow — HUMAN-ONLY, idempotent.
# Generated by /slipway:bootstrap from .slipway/config.yaml (re-scaffold with --force to refresh).
#
#   bash .slipway/setup-azure.sh            # preflight + dry run: prints what would change, changes nothing
#   bash .slipway/setup-azure.sh --apply    # create/assign what is missing
#   bash .slipway/setup-azure.sh --apply --set-github-secrets   # also push AZURE_* secrets with gh
#
# What it creates: Entra app registration + service principal with two federated credentials (OIDC, no client
# secret), the Terraform state storage (Entra-only auth), the environment resource group, and least-privilege
# role assignments for the CI/CD principal and for you. It does NOT create ACR, Key Vault or the identity used by
# the apps: those belong to infra/foundation (Terraform). It never prints or stores a secret.
set -euo pipefail

APPLY=false; SET_SECRETS=false
for a in "$@"; do case "$a" in --apply) APPLY=true;; --set-github-secrets) SET_SECRETS=true;; -h|--help) sed -n '2,14p' "$0"; exit 0;; *) echo "unknown arg: $a" >&2; exit 2;; esac; done

# ---- names from .slipway/config.yaml ----
PROJECT="taskflow"
LOCATION="westeurope"
RG="rg-taskflow-dev"
STATE_RG="rg-taskflow-tfstate"
STATE_SA="sttaskflowtf"
STATE_CONTAINER="tfstate"
GH_OWNER="integranz"; GH_REPO="taskflow"; GH_BRANCH="main"; GH_ENV="dev"
APP_NAME="sp-${PROJECT}-github"
ISSUER="https://token.actions.githubusercontent.com"
AUDIENCE="api://AzureADTokenExchange"

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  ok    %s\n' "$*"; }
todo() { printf '  %s %s\n' "$($APPLY && echo 'apply' || echo 'would ')" "$*"; }
run()  { if $APPLY; then "$@"; else printf '        $ %s\n' "$*"; fi; }

# ---- preflight ----
say "Preflight"
command -v az >/dev/null || { echo "az CLI not installed" >&2; exit 1; }
SUB_ID=$(az account show --query id -o tsv 2>/dev/null) || { echo "not logged in: az login && az account set --subscription <id>" >&2; exit 1; }
TENANT_ID=$(az account show --query tenantId -o tsv); SUB_NAME=$(az account show --query name -o tsv)
ok "subscription: $SUB_NAME ($SUB_ID)"
ME_ID=$(az ad signed-in-user show --query id -o tsv); ME_UPN=$(az ad signed-in-user show --query userPrincipalName -o tsv); ok "user: $ME_UPN"
CAN_CREATE_APPS=$(az rest --method GET --url "https://graph.microsoft.com/v1.0/policies/authorizationPolicy" --query defaultUserRolePermissions.allowedToCreateApps -o tsv 2>/dev/null || echo unknown)
DIR_ROLES=$(az rest --method GET --url "https://graph.microsoft.com/v1.0/me/memberOf/microsoft.graph.directoryRole" --query "value[].displayName" -o tsv 2>/dev/null | tr '\n' ',' || true)
if [ "$CAN_CREATE_APPS" = "true" ] || echo "$DIR_ROLES" | grep -Eq 'Application Administrator|Cloud Application Administrator|Global Administrator'; then ok "can register applications (allowedToCreateApps=$CAN_CREATE_APPS; roles: ${DIR_ROLES:-none})"
else echo "  FAIL  cannot register applications: tenant policy allowedToCreateApps=$CAN_CREATE_APPS and no Application Administrator role. Ask a Cloud Application Administrator to run steps 1-2 or grant the role." >&2; PRE_FAIL=1; fi
SUB_ROLES=$(az role assignment list --assignee "$ME_ID" --all --include-inherited --query "[?scope=='/subscriptions/$SUB_ID' || scope=='/'].roleDefinitionName" -o tsv | sort -u | tr '\n' ',')
if echo "$SUB_ROLES" | grep -Eq 'Owner|User Access Administrator'; then ok "can assign roles at subscription scope (roles: $SUB_ROLES)"
else echo "  WARN  no Owner/User Access Administrator on the subscription (roles: ${SUB_ROLES:-none}); role assignments in step 5 will fail unless you hold those roles on the target resource groups." >&2; fi
if echo "$SUB_ROLES" | grep -Eq 'Owner|Contributor'; then ok "can create resource groups"; else echo "  FAIL  need Contributor or Owner on the subscription to create resource groups" >&2; PRE_FAIL=1; fi
FORBIDDEN_ROLE_IDS=$(az role assignment list --assignee "$ME_ID" --all --include-inherited --query "[?condition!=null && (roleDefinitionName=='User Access Administrator' || roleDefinitionName=='Owner')].condition" -o tsv 2>/dev/null | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | sort -u | tr '\n' ' ' || true)
if [ -n "$FORBIDDEN_ROLE_IDS" ]; then
  FORBIDDEN_ROLE_NAMES=""; for g in $FORBIDDEN_ROLE_IDS; do FORBIDDEN_ROLE_NAMES="$FORBIDDEN_ROLE_NAMES$(az role definition list --name "$g" --query "[0].roleName" -o tsv 2>/dev/null), "; done
  ok "your role-assignment rights carry an ABAC condition: you cannot assign ${FORBIDDEN_ROLE_NAMES%, }. This script assigns only Contributor and Storage Blob Data Contributor, which are allowed."
fi
[ "${PRE_FAIL:-0}" = 0 ] || { echo "preflight failed; nothing changed" >&2; exit 1; }
$APPLY || say "Dry run (add --apply to execute). Commands that would run:"

# ---- 1. app registration + service principal ----
say "1. App registration $APP_NAME"
APP_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv)
if [ -n "$APP_ID" ]; then ok "exists: appId $APP_ID"; else todo "create app registration"; run az ad app create --display-name "$APP_NAME" --sign-in-audience AzureADMyOrg --query appId -o tsv; $APPLY && APP_ID=$(az ad app list --display-name "$APP_NAME" --query "[0].appId" -o tsv); fi
if [ -n "${APP_ID:-}" ]; then
  APP_OBJ=$(az ad app show --id "$APP_ID" --query id -o tsv)
  SP_ID=$(az ad sp list --filter "appId eq '$APP_ID'" --query "[0].id" -o tsv)
  if [ -n "$SP_ID" ]; then ok "service principal exists: $SP_ID"; else todo "create service principal"; run az ad sp create --id "$APP_ID"; $APPLY && SP_ID=$(az ad sp list --filter "appId eq '$APP_ID'" --query "[0].id" -o tsv); fi
fi

# ---- 2. federated credentials ----
say "2. Federated credentials (issuer $ISSUER, audience $AUDIENCE)"
# GitHub's OIDC subject prefix. Repositories with "immutable subject claims" present
#   repo:<owner>@<owner-id>/<repo>@<repo-id>:...   instead of   repo:<owner>/<repo>:...
# Entra matches subjects literally, so read the prefix GitHub will actually send.
SUB_PREFIX="repo:${GH_OWNER}/${GH_REPO}"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  CUSTOM=$(gh api "repos/${GH_OWNER}/${GH_REPO}/actions/oidc/customization/sub" 2>/dev/null || true)
  IMMUTABLE=$(printf '%s' "$CUSTOM" | python3 -c 'import json,sys; d=json.load(sys.stdin); print("true" if d.get("use_immutable_subject") else "false")' 2>/dev/null || echo unknown)
  PREFIX_FROM_GH=$(printf '%s' "$CUSTOM" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("sub_claim_prefix",""))' 2>/dev/null || true)
  if [ "$IMMUTABLE" = "true" ] && [ -n "$PREFIX_FROM_GH" ]; then SUB_PREFIX="$PREFIX_FROM_GH"; ok "GitHub uses immutable OIDC subjects: prefix $SUB_PREFIX"; else ok "GitHub OIDC subject prefix: $SUB_PREFIX (immutable subjects: $IMMUTABLE)"; fi
else
  IDS=$(curl -fsS "https://api.github.com/repos/${GH_OWNER}/${GH_REPO}" 2>/dev/null || true)
  if [ -n "$IDS" ]; then
    SUB_PREFIX_IMMUTABLE=$(printf '%s' "$IDS" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(f"repo:{d[\"owner\"][\"login\"]}@{d[\"owner\"][\"id\"]}/{d[\"name\"]}@{d[\"id\"]}")' 2>/dev/null || true)
    echo "  WARN  gh not available: cannot read the repository's OIDC subject setting. Adding credentials for both the classic prefix and the immutable one ($SUB_PREFIX_IMMUTABLE)." >&2
  fi
fi
fed() { # name subject
  local name="$1" subject="$2" existing='[]' stale=""
  if [ -n "${APP_OBJ:-}" ]; then existing=$(az ad app federated-credential list --id "$APP_OBJ" -o json 2>/dev/null || echo '[]'); fi
  if printf '%s' "$existing" | python3 -c 'import json,sys; s=sys.argv[1]; sys.exit(0 if any(c.get("subject")==s for c in json.load(sys.stdin)) else 1)' "$subject" 2>/dev/null; then ok "$name: $subject"; return; fi
  local params="{\"name\":\"$name\",\"issuer\":\"$ISSUER\",\"subject\":\"$subject\",\"audiences\":[\"$AUDIENCE\"]}"
  stale=$(printf '%s' "$existing" | python3 -c 'import json,sys; n=sys.argv[1]; print(next((c.get("subject","") for c in json.load(sys.stdin) if c.get("name")==n), ""))' "$name" 2>/dev/null || true)
  if [ -n "$stale" ]; then
    # Same name, different subject: usually the repository was renamed (GitHub's immutable subject embeds the
    # repository name). The old subject can never match again, so replace it in place instead of failing on the name.
    todo "update $name: $stale -> $subject"
    run az ad app federated-credential update --id "$APP_OBJ" --federated-credential-id "$name" --parameters "$params"
    return
  fi
  todo "add $name: $subject"
  run az ad app federated-credential create --id "${APP_OBJ:-<app-object-id>}" --parameters "$params"
}
SUFFIX=""; [ "$SUB_PREFIX" != "repo:${GH_OWNER}/${GH_REPO}" ] && SUFFIX="-immutable"
fed "github-${GH_BRANCH//\//-}${SUFFIX}" "${SUB_PREFIX}:ref:refs/heads/${GH_BRANCH}"
fed "github-env-${GH_ENV}${SUFFIX}"      "${SUB_PREFIX}:environment:${GH_ENV}"
if [ -n "${SUB_PREFIX_IMMUTABLE:-}" ] && [ "$SUB_PREFIX_IMMUTABLE" != "$SUB_PREFIX" ]; then
  fed "github-${GH_BRANCH//\//-}-immutable" "${SUB_PREFIX_IMMUTABLE}:ref:refs/heads/${GH_BRANCH}"
  fed "github-env-${GH_ENV}-immutable"       "${SUB_PREFIX_IMMUTABLE}:environment:${GH_ENV}"
fi

# ---- 3. terraform state storage (Entra-only auth) ----
say "3. Terraform state: $STATE_RG / $STATE_SA / $STATE_CONTAINER"
az group show -n "$STATE_RG" >/dev/null 2>&1 && ok "resource group $STATE_RG" || { todo "create resource group $STATE_RG"; run az group create -n "$STATE_RG" -l "$LOCATION" -o none; }
if az storage account show -n "$STATE_SA" -g "$STATE_RG" >/dev/null 2>&1; then ok "storage account $STATE_SA"
else todo "create storage account $STATE_SA (shared key disabled)"; run az storage account create -n "$STATE_SA" -g "$STATE_RG" -l "$LOCATION" --sku Standard_LRS --kind StorageV2 --min-tls-version TLS1_2 --allow-blob-public-access false --allow-shared-key-access false -o none; fi
SA_SCOPE="/subscriptions/$SUB_ID/resourceGroups/$STATE_RG/providers/Microsoft.Storage/storageAccounts/$STATE_SA"
CONTAINER_SCOPE="$SA_SCOPE/blobServices/default/containers/$STATE_CONTAINER"

# ---- 4. environment resource group ----
say "4. Resource group $RG"
az group show -n "$RG" >/dev/null 2>&1 && ok "resource group $RG" || { todo "create resource group $RG"; run az group create -n "$RG" -l "$LOCATION" -o none; }
RG_SCOPE="/subscriptions/$SUB_ID/resourceGroups/$RG"

# ---- 5. role assignments ----
say "5. Role assignments (least privilege)"
has_role() { # principal-object-id role scope -> 0 if the principal holds the role at this scope or inherits it from above
  [ -n "$1" ] && [ "$(az role assignment list --assignee "$1" --scope "$3" --include-inherited --query "[?roleDefinitionName=='$2'] | length(@)" -o tsv 2>/dev/null || echo 0)" != "0" ]
}
assign() { # principal-object-id principal-type role scope label [soft]
  local pid="$1" ptype="$2" role="$3" scope="$4" label="$5" soft="${6:-}"
  if has_role "$pid" "$role" "$scope"; then ok "$label: $role (held or inherited)"; return 0; fi
  todo "$label: $role on ${scope#/subscriptions/$SUB_ID/}"
  if [ -n "$soft" ] && $APPLY; then
    az role assignment create --assignee-object-id "${pid}" --assignee-principal-type "$ptype" --role "$role" --scope "$scope" -o none 2>/tmp/slipway-assign.err \
      || echo "  WARN  could not assign $role to $label ($(grep -oE '\([A-Za-z]+\)' /tmp/slipway-assign.err | head -1)); continuing because this role is for you, not for CI/CD. Grant it another way if a later step needs it." >&2
    return 0
  fi
  run az role assignment create --assignee-object-id "${pid:-<sp-object-id>}" --assignee-principal-type "$ptype" --role "$role" --scope "$scope" -o none
}
# the human: create the state container, apply infra/foundation (which creates non-privileged role assignments), set Key Vault values.
# Privileged roles (Owner / User Access Administrator) are never assigned by this script: if you hold one at subscription
# scope it is inherited; if not, ask a subscription Owner. Your own assignments are soft: a failure warns and continues.
assign "$ME_ID" User "Storage Blob Data Contributor" "$SA_SCOPE" "you" soft
if has_role "$ME_ID" "User Access Administrator" "$RG_SCOPE" || has_role "$ME_ID" "Owner" "$RG_SCOPE"; then ok "you: can create role assignments in $RG (inherited)"
else echo "  WARN  you hold neither Owner nor User Access Administrator over $RG; infra/foundation (UAMI -> AcrPull, Key Vault Secrets User) will need a subscription Owner to grant you one of them." >&2; fi
# the CI/CD principal
assign "${SP_ID:-}" ServicePrincipal "Contributor"                   "$RG_SCOPE"        "sp"
assign "${SP_ID:-}" ServicePrincipal "Storage Blob Data Contributor" "$CONTAINER_SCOPE" "sp"
# state container needs the data-plane role above; create it last
if az storage container show -n "$STATE_CONTAINER" --account-name "$STATE_SA" --auth-mode login >/dev/null 2>&1; then ok "container $STATE_CONTAINER"
elif $APPLY; then
  todo "create container $STATE_CONTAINER (RBAC propagation can take ~1 min; retrying)"; for i in 1 2 3 4 5 6; do az storage container create -n "$STATE_CONTAINER" --account-name "$STATE_SA" --auth-mode login -o none 2>/dev/null && break || sleep 10; done; az storage container show -n "$STATE_CONTAINER" --account-name "$STATE_SA" --auth-mode login >/dev/null
else todo "create container $STATE_CONTAINER"; run az storage container create -n "$STATE_CONTAINER" --account-name "$STATE_SA" --auth-mode login -o none; fi

# ---- 6. outputs ----
say "6. Values for GitHub (identifiers, not secrets; stored as secrets so they stay out of public logs)"
printf '  AZURE_CLIENT_ID=%s\n  AZURE_TENANT_ID=%s\n  AZURE_SUBSCRIPTION_ID=%s\n' "${APP_ID:-<after --apply>}" "$TENANT_ID" "$SUB_ID"
if $SET_SECRETS && $APPLY; then
  command -v gh >/dev/null || { echo "gh not installed; set the secrets manually" >&2; exit 1; }
  printf '%s' "$APP_ID"    | gh secret set AZURE_CLIENT_ID       -R "$GH_OWNER/$GH_REPO"
  printf '%s' "$TENANT_ID" | gh secret set AZURE_TENANT_ID       -R "$GH_OWNER/$GH_REPO"
  printf '%s' "$SUB_ID"    | gh secret set AZURE_SUBSCRIPTION_ID -R "$GH_OWNER/$GH_REPO"
  ok "GitHub secrets set on $GH_OWNER/$GH_REPO"
else
  printf '  Then:  printf %%s "$AZURE_CLIENT_ID" | gh secret set AZURE_CLIENT_ID -R %s/%s   (same for TENANT and SUBSCRIPTION), or re-run with --apply --set-github-secrets\n' "$GH_OWNER" "$GH_REPO"
fi
printf '  Still manual: gh secret set DOCKERHUB_TOKEN -R %s/%s ; gh variable set DOCKERHUB_USERNAME -R %s/%s --body <user> ; environment "%s" with a required reviewer.\n' "$GH_OWNER" "$GH_REPO" "$GH_OWNER" "$GH_REPO" "$GH_ENV"
say "Done$($APPLY || echo ' (dry run)'). Next: /slipway:plan dev --layer foundation"
